### ISSUE TITLE
Error updating the user

### ISSUE THREAD

**Issue by bekjon-me** [Jahongir-Qurbonov/TodoAPI#8]
## A user with that username already exists
- When I try to update the user via patch or put method, it gives the error that says, **a user with that username already exists**. So when the users want to update their profile, they must update their username too, it shouldn't work that way, please fix that problem and tag me when you update it.
- And it would be great if you could add a profile image that will be shown on the profile page. ( aka profile photo )

**Comment by Jahongir-Qurbonov** [comment]
The reason for the problem is that you could not use it yourself
